/* Auto-logout @ midnight + daily codes */
const STORAGE_KEY="elves-humint-session";
const LAST_LOGIN_KEY="elves-last-login-date";
const DAILY_CODES={
  "2025-12-01":"ELF1","2025-12-02":"ELF2","2025-12-03":"ELF3","2025-12-04":"ELF4","2025-12-05":"ELF5","2025-12-06":"ELF6",
  "2025-12-07":"ELF7","2025-12-08":"ELF8","2025-12-09":"ELF9","2025-12-10":"ELF10","2025-12-11":"ELF11","2025-12-12":"ELF12",
  "2025-12-13":"ELF13","2025-12-14":"ELF14","2025-12-15":"ELF15","2025-12-16":"ELF16","2025-12-17":"ELF17","2025-12-18":"ELF18",
  "2025-12-19":"ELF19","2025-12-20":"ELF20","2025-12-21":"ELF21","2025-12-22":"ELF22","2025-12-23":"ELF23","2025-12-24":"ELF24"
};
const qp=new URLSearchParams(location.search);
function todayISO(){return new Date().toISOString().split("T")[0]}
function load(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY))||{agent:{name:null},session:{loggedIn:false},outboxHistory:[]}}catch{return {agent:{name:null},session:{loggedIn:false},outboxHistory:[]}}}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}
const state=load();if(!state.session)state.session={loggedIn:false};if(!Array.isArray(state.outboxHistory))state.outboxHistory=[];
(function(){const t=new Date().toDateString();const last=localStorage.getItem(LAST_LOGIN_KEY);if(last&&last!==t){state.session.loggedIn=false;localStorage.setItem(STORAGE_KEY,JSON.stringify(state));}localStorage.setItem(LAST_LOGIN_KEY,t)})();
if(qp.get('force')==='login'){state.session.loggedIn=false;localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}
const $=s=>document.querySelector(s);
const $login=$("#login"),$chat=$("#chat"),$history=$("#history"),$inbox=$("#inbox"),$inboxStatus=$("#inboxStatus"),$chatInput=$("#chatInput"),$fileInput=$("#fileInput"),$sendBtn=$("#sendBtn"),$clearBtn=$("#clearBtn"),$reportHistory=$("#reportHistory"),$agentName=$("#agentNameInput"),$dayCode=$("#dayCodeInput"),$btnLogin=$("#doLoginBtn");
const normalize=s=>(s||'').toString().trim().toUpperCase();const safe=s=>String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');
function dagensKode(){const ov=qp.get('code');if(ov)return normalize(ov);const key=todayISO();return normalize(DAILY_CODES[key]||"ELF1")}
function revealApp(){$chat?.classList.remove('hidden');$history?.classList.remove('hidden')}function hideApp(){$chat?.classList.add('hidden');$history?.classList.add('hidden')}
if(state.session.loggedIn){$login?.classList.add('hidden');revealApp();fetchInbox();renderHistory()}else{hideApp();$login?.classList.remove('hidden')}
if(state.agent?.name)$agentName.value=state.agent.name;
$btnLogin?.addEventListener('click',()=>{const name=($agentName.value||'').trim();const entered=normalize($dayCode.value);const correct=dagensKode();const msg=document.getElementById('loginMsg');if(entered!==correct){if(msg)msg.textContent='Feil feltkode for dagens oppdrag.';return}if(name)state.agent={name};state.session.loggedIn=true;save();$login?.classList.add('hidden');revealApp();if(msg)msg.textContent='';$inboxStatus.textContent=`Innlogget som ${state.agent.name||'AGENT'}. Laster innboks…`;fetchInbox();renderHistory()});
async function fetchInbox(){try{const res=await fetch('/api/inbox?ts='+Date.now());if(!res.ok)throw new Error(res.statusText);let data=await res.json();const now=Date.now();data=(Array.isArray(data)?data:[]).filter(m=>!m.availableAt||m.availableAt<=now);renderInbox(data);$inboxStatus.textContent='Innboks oppdatert: '+new Date().toLocaleString()}catch{$inboxStatus.textContent='Kunne ikke laste innboks.'}}
function renderInbox(items=[]){$inbox.innerHTML='';if(!items.length){$inbox.innerHTML='<div class="muted">Ingen meldinger enda.</div>';return}items.sort((a,b)=>(a.ts||0)-(b.ts||0));for(const m of items){const w=document.createElement('div');w.className='msg';w.innerHTML=`<div class="msgHead"><strong>${safe(m.from||'ELVES HQ')}</strong><span class="muted">${m.ts?new Date(m.ts).toLocaleString():''}</span></div>${m.title?`<div class="msgTitle">${safe(m.title)}</div>`:''}${m.text?`<div class="msgText">${safe(m.text)}</div>`:''}${m.id?`<div class="msgMeta">ID: ${safe(m.id)}</div>`:''}`;if(m.media&&m.media.url&&m.media.type){const t=m.media.type,u=m.media.url,cap=m.media.caption?`<div class="muted">${safe(m.media.caption)}</div>`:'';if(t==='image'){const img=document.createElement('img');img.src=m.media.thumb_url||u;img.alt=m.media.caption||'';img.className='msgImg';w.appendChild(img);if(cap)w.insertAdjacentHTML('beforeend',cap)}if(t==='audio'){const a=document.createElement('audio');a.controls=true;a.src=u;w.appendChild(a);if(cap)w.insertAdjacentHTML('beforeend',cap)}if(t==='video'){const v=document.createElement('video');v.controls=true;v.playsInline=true;v.src=u;v.className='msgVid';w.appendChild(v);if(cap)w.insertAdjacentHTML('beforeend',cap)}if(t==='youtube'){const mId=u.match(/(?:youtu\.be\/|v=)([A-Za-z0-9_-]{6,})/);const vid=mId?mId[1]:null;if(vid){const ifr=document.createElement('iframe');ifr.width='100%';ifr.height='315';ifr.style.border='0';ifr.allow='accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share';ifr.allowFullscreen=true;ifr.src=`https://www.youtube.com/embed/${vid}?rel=0`;w.appendChild(ifr);if(cap)w.insertAdjacentHTML('beforeend',cap)}}if(t==='vimeo'){const vm=u.match(/vimeo\.com\/(\d+)/);const vid=vm?vm[1]:null;if(vid){const ifr=document.createElement('iframe');ifr.width='100%';ifr.height='315';ifr.style.border='0';ifr.allow='autoplay; fullscreen; picture-in-picture';ifr.allowFullscreen=true;ifr.src=`https://player.vimeo.com/video/${vid}`;w.appendChild(ifr);if(cap)w.insertAdjacentHTML('beforeend',cap)}}}$inbox.appendChild(w)}}
setInterval(()=>{if(state.session.loggedIn)fetchInbox()},60*1000);
function formElement(){return document.querySelector('form[name="agent-chat"][data-netlify]')}
async function sendViaNetlifyForms(text,file){const f=formElement();if(f){const fd=new FormData(f);fd.set('message',text||'');fd.set('agent',state.agent?.name||'');if(file)fd.set('file',file,file.name);const res=await fetch('/',{method:'POST',body:fd});if(!res.ok)throw new Error('Submit-feil');return true}const fd=new FormData();fd.set('form-name','agent-chat');fd.set('message',text||'');fd.set('agent',state.agent?.name||'');if(file)fd.set('file',file,file.name);const res=await fetch('/',{method:'POST',body:fd});if(!res.ok)throw new Error('Submit-feil');return true}
$sendBtn?.addEventListener('click',async()=>{if(!state.session.loggedIn)return;const text=($chatInput.value||'').trim();const file=$fileInput.files&&$fileInput.files[0]?$fileInput.files[0]:null;if(!text&&!file){alert('Skriv en melding eller legg ved fil.');return}$sendBtn.disabled=true;$sendBtn.textContent='Sender…';try{await sendViaNetlifyForms(text,file);state.outboxHistory.push({ts:Date.now(),title:text.slice(0,80)||(file?`Sendte fil: ${file.name}`:'Melding'),body:text,file:file?file.name:null});if(state.outboxHistory.length>200)state.outboxHistory.splice(0,state.outboxHistory.length-200);save();renderHistory();$chatInput.value='';if($fileInput)$fileInput.value=''}catch{alert('Kunne ikke sende meldingen.')}finally{$sendBtn.disabled=false;$sendBtn.textContent='SEND';fetchInbox()}});
$clearBtn?.addEventListener('click',()=>{$chatInput.value='';if($fileInput)$fileInput.value=''});
function renderHistory(){if(!state.outboxHistory.length){$reportHistory.textContent='Ingen rapporter enda.';return}const html=state.outboxHistory.slice().sort((a,b)=>(a.ts||0)-(b.ts||0)).map(r=>{const ts=new Date(r.ts).toLocaleString(),title=safe(r.title||'Melding'),body=safe(r.body||''),file=r.file?`<div class="muted">Fil: ${safe(r.file)}</div>`:'';return `<div class="histItem"><div class="histHead"><strong>${title}</strong><span class="muted">${ts}</span></div>${body?`<div class="histText">${body}</div>`:''}${file}</div>`}).join('');$reportHistory.innerHTML=html}
if('serviceWorker'in navigator){window.addEventListener('load',()=>{navigator.serviceWorker.register('/service-worker.js').catch(()=>{})})}
