[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/inbox"
  to = "/.netlify/functions/inbox"
  status = 200

[[redirects]]
  from = "/api/upload-media"
  to = "/.netlify/functions/upload-media"
  status = 200

[[redirects]]
  from = "/api/media/:id"
  to = "/.netlify/functions/media?id=:id"
  status = 200

# Scheduled publish every minute
[[scheduled.functions]]
  name = "scheduler"
  cron = "*/1 * * * *"
